### ISSUE TITLE
save method not work

### ISSUE THREAD

**Issue by zodman** [fitnr/twitter_bot_utils#5]
Traceback (most recent call last):
  File "/home/zodman/.local/bin/tbu", line 9, in <module>
    load_entry_point('twitter-bot-utils==0.11.1', 'console_scripts', 'tbu')()
  File "/home/zodman/.local/lib/python2.7/site-packages/twitter_bot_utils/cli.py", line 187, in main
    arguments.func(arguments)
  File "/home/zodman/.local/lib/python2.7/site-packages/twitter_bot_utils/cli.py", line 109, in authenticate
    section = config['users'][auth.get_username()]
UnboundLocalError: local variable 'config' referenced before assignment

**Comment by fitnr** [comment]
The idea was that `--save` applied to a passed file, but I can see how that would be confusing. It will now accept a file path if you want to create a new config file.
